version: '3'
services:
  mysql:
    image: mysql:5.6
    container_name: deb2-gandauth-database
    ports:
      - 3307:3307
    expose:
      - 3307
    volumes:
      - "mysql_data:/var/lib/mysql"
      - "mysql_config:/etc/"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - deb2

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - deb2

#  kafka:
#    image: johnnypark/kafka-zookeeper
#    container_name: deb2-kafka
#    ports:
#      - 9092:9092
#      - 2181:2181
#    networks:
#      - deb2
#
#  maxwell:
#    image: debitos2productionne001.azurecr.io/acr-d2-stg-cmp-maxwell:latest
#    command: ["bin/maxwell", "--log_level=DEBUG", "--producer=kafka", "--kafka.bootstrap.servers=kafka:9092",  "--user=root","--password=root", "--host=mysql", "--port=3307", "--kafka_topic", "%{database}_%{table}", "--filter=exclude: *.*, include: debitos_staging.ilance_users"]
#    container_name: deb2-gandauth-maxwell
#    depends_on:
#      - kafka
#      - mysql
#    networks:
#      - deb2
#
#  ganduath-consumer:
#    image: debitos2productionne001.azurecr.io/acr-d2-stg-ms-gandauth:latest
#    container_name: deb2-gandauth-kafka-consumer
#    build: .
#    command: ["python", "manage.py", "startconsumer"]
#    depends_on:
#      - kafka
#    links:
#      - kafka
#    volumes:
#      - "/opt/debitos/ms/debitos.2.0.ms.gandauth/gandauth:/usr/src/app"
#    environment:
#      - KAFKA_EMAIL_TOPIC=debitos_staging_ilance_users
#      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
#      - KAFKA_EMAIL_GROUP_ID=ilance-maxwell-users
#      - DATABASE_USER=root
#      - DATABASE_PASSWORD=root
#      - DATABASE_HOST=mysql
#      - DATABASE_PORT=3307
#      - KAFKA_SECURITY_PROTOCOL=PLAINTEXT
#      - DEBUG=1
#    networks:
#      - deb2

  ganduath-app:
    image: debitos2productionne001.azurecr.io/acr-d2-stg-ms-gandauth:latest
    container_name: deb2-gandauth-app
    build: .
    command: [ "python", "manage.py", "runserver", "0.0.0.0:80"]
    depends_on:
      - mysql
      - redis
    volumes:
      - "/opt/debitos/ms/debitos.2.0.ms.gandauth/gandauth:/usr/src/app"
      - "/opt/debitos/ms/debitos.2.0.ms.gandauth/staticfiles:/usr/src/app/staticfiles"
    expose:
      - 80
    environment:
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=mysql
      - DATABASE_PORT=3307
      - GANDAUTH_CACHE_BACKEND=django_redis.cache.RedisCache
      - GANDAUTH_REDIS_CACHE_LOCATION=redis://redis:6379/
      - GANDAUTH_STAGING=1
      - DEBUG=1
      - GANDAUTH_ENVIRONMENT='dev'
    networks:
      - deb2

  # ilance
  ilance-web:
    image: ilanceregistryprd.azurecr.io/ilance:latest
    container_name: deb2-ilance-web
    privileged: true
    depends_on:
      - mysql
    volumes:
      - /opt/debitos/ilance/ilance:/var/www/html
    environment:
      - DEBITOS_CRON_URL=http://dev.market.debitos.local/cron.php
      - DEBITOS_DB_SERVER=mysql
      - DEBITOS_DB_SERVER_PASSWORD=root
      - DEBITOS_DB_SERVER_PORT=3307
      - DEBITOS_DB_SERVER_USERNAME=root
      - DEBITOS_DB_DATABASE=debitos_staging
      - DEBITOS_DIR_SERVER_ROOT=/var/www/html/
      - DEBITOS_ENVIRONMENT=development
      - DEBITOS_HTTPS_SERVER=http://dev.market.debitos.local/
      - DEBITOS_HTTP_SERVER=http://dev.market.debitos.local/
      - DEBITOS_MANDRILL_SUBACCOUNT=wojtek
      - DEBITOS_SMTP_PASS=PqGc8um2NFA5czHGp3X4eA
      - DEBITOS_SMTP_USER=peters@debitos.de
    networks:
      - deb2

  # nginx
  ninx:
    image: debitos2productionne001.azurecr.io/acr-d2-cmp-nginx-gateway:latest
    container_name: deb2-nginx-gateway
    hostname: dev.market.debitos.local
    depends_on:
      - ilance-web
      - ganduath-app
    ports:
      - 80:80
      - 443:443
    volumes:
      - "/opt/debitos/ms/debitos.2.0.ms.gandauth/nginx/logs:/etc/nginx/logs"
      - "/opt/debitos/ms/debitos.2.0.ms.gandauth/nginx/routes:/etc/nginx/proxies/proxy-routes"
    networks:
      deb2:
        aliases:
          - dev.market.debitos.local
          - localhost
volumes:
  mysql_data:
  mysql_config:

networks:
  deb2: